Add p0-input-image
gauravsinhaweb/Pixel-UI pull request #3
Opened 2022-02-05 21:06 UTC by gauravsinhaweb

Add: add p0-input-image

2022-02-05 21:39 UTC, PuneetP16 approved these changes
Looks good to merge

2022-02-06 04:33 UTC, sri-rishi commented
Look good to merge

2022-02-06 04:34 UTC, anasm11 commented
The code looks good. The input box cant be recognised at first glance, maybe adding border would help.

2022-02-06 04:36 UTC, sri-rishi approved these changes
Looks good to merge

2022-02-06 08:16 UTC, Ankur9669 requested changes
The UI and code looks great, just do these changes and it would be great to merge

2022-02-06 08:16 UTC, Ankur9669 commented on components/image/image.css
> +}
You can add object-fit property here

2022-02-06 08:16 UTC, Ankur9669 commented on components/input/input.css
> +}
All your inputs are of width:100%.
So you can add width: 100% to you basic_inp class instead of adding everywhere.

2022-02-06 15:18 UTC, gauravsinhaweb commented
> The code looks good. The input box cant be recognised at first glance, maybe adding border would help.

Updated the changes, thanks!

2022-02-06 15:18 UTC, gauravsinhaweb commented
> 

Updated the changes, thanks!

2022-02-06 15:19 UTC, merged